// Login and registration share a focused, public layout.
import { Link, useNavigate } from "react-router-dom";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import toast from "react-hot-toast";
import { useAuth } from "../context/AuthContext";
import { backendErrors, errorMessage } from "../utils/helpers";
import { Button, Input, Spinner } from "../components/ui";
const passwordRule = z.string().min(8, "Use at least 8 characters").regex(/[A-Za-z]/, "Include a letter").regex(/\d/, "Include a number");
const loginSchema = z.object({ email: z.string().email("Enter a valid email"), password: z.string().min(1, "Password is required") });
const registerSchema = loginSchema.extend({ fullName: z.string().min(2, "Full name needs at least 2 characters"), password: passwordRule, confirmPassword: z.string() }).refine((v) => v.password === v.confirmPassword, { message: "Passwords must match", path: ["confirmPassword"] });
function Shell({ title, children, footer }: { title: string; children: React.ReactNode; footer: React.ReactNode }) { return <main className="grid min-h-screen place-items-center bg-slate-50 p-4"><section className="w-full max-w-md rounded-2xl bg-white p-7 shadow-sm ring-1 ring-slate-200"><h1 className="text-2xl font-bold text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">ProjectFlow keeps your work organized.</p><div className="mt-6">{children}</div><p className="mt-5 text-center text-sm text-slate-600">{footer}</p></section></main>; }
export function LoginPage() { const { login } = useAuth(); const navigate = useNavigate(); const { register, handleSubmit, setError, formState: { errors, isSubmitting } } = useForm<z.infer<typeof loginSchema>>({ resolver: zodResolver(loginSchema) }); const submit = async (v: z.infer<typeof loginSchema>) => { try { await login(v.email, v.password); toast.success("Welcome back!"); navigate("/dashboard"); } catch (e) { backendErrors(e).forEach(({ field, message }) => setError(field as "email" | "password", { message })); toast.error(errorMessage(e)); } }; return <Shell title="Welcome back" footer={<>New here? <Link className="font-semibold text-indigo-600" to="/register">Create an account</Link></>}><form className="space-y-4" onSubmit={handleSubmit(submit)}><label className="block text-sm font-medium">Email<Input type="email" {...register("email")} /></label>{field(errors.email?.message)}<label className="block text-sm font-medium">Password<Input type="password" {...register("password")} /></label>{field(errors.password?.message)}<Button className="w-full" type="submit" disabled={isSubmitting}>{isSubmitting ? <Spinner label="Signing in" /> : "Sign in"}</Button></form></Shell>; }
export function RegisterPage() { const { register: signUp } = useAuth(); const navigate = useNavigate(); const { register, handleSubmit, setError, formState: { errors, isSubmitting } } = useForm<z.infer<typeof registerSchema>>({ resolver: zodResolver(registerSchema) }); const submit = async (v: z.infer<typeof registerSchema>) => { try { await signUp(v.fullName, v.email, v.password); toast.success("Account created!"); navigate("/dashboard"); } catch (e) { backendErrors(e).forEach(({ field: name, message }) => setError(name as keyof z.infer<typeof registerSchema>, { message })); toast.error(errorMessage(e)); } }; return <Shell title="Create your account" footer={<>Already registered? <Link className="font-semibold text-indigo-600" to="/login">Sign in</Link></>}><form className="space-y-3" onSubmit={handleSubmit(submit)}>{([ ["fullName", "Full name", "text"], ["email", "Email", "email"], ["password", "Password", "password"], ["confirmPassword", "Confirm password", "password"] ] as const).map(([name, label, type]) => <div key={name}><label className="block text-sm font-medium">{label}<Input type={type} {...register(name)} /></label>{field(errors[name]?.message)}</div>)}<Button className="w-full" type="submit" disabled={isSubmitting}>{isSubmitting ? <Spinner label="Creating" /> : "Create account"}</Button></form></Shell>; }
const field = (text?: string) => text && <p className="mt-1 text-xs text-rose-600">{text}</p>;
