// Project listing supports server-side filtering, debounced search, and pagination.
import { useCallback, useEffect, useState } from "react";
import { Link } from "react-router-dom";
import toast from "react-hot-toast";
import { projectService } from "../services/projectService";
import { useDebounce } from "../hooks/useDebounce";
import type { Pagination as PaginationType, Project, ProjectStatus } from "../types";
import { showDate, errorMessage } from "../utils/helpers";
import { Badge, Button, ConfirmDialog, EmptyState, ErrorState, Modal, Pagination, Select, Skeleton } from "../components/ui";
import { ProjectForm } from "../components/forms";
const tone = (status: ProjectStatus) => status === "COMPLETED" ? "green" : status === "IN_PROGRESS" ? "blue" : "yellow";
export function ProjectsPage() { const [projects, setProjects] = useState<Project[]>([]); const [pagination, setPagination] = useState<PaginationType | null>(null); const [search, setSearch] = useState(""); const deferred = useDebounce(search); const [status, setStatus] = useState<ProjectStatus | "">(""); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false); const [form, setForm] = useState<Project | "new" | null>(null); const [remove, setRemove] = useState<Project | null>(null); const [deleting, setDeleting] = useState(false);
  const load = useCallback(() => { setLoading(true); setFailed(false); projectService.list({ search: deferred, status, page, limit: 9 }).then((r) => { setProjects(r.projects); setPagination(r.pagination); }).catch(() => setFailed(true)).finally(() => setLoading(false)); }, [deferred, status, page]); useEffect(() => load(), [load]); useEffect(() => setPage(1), [deferred, status]);
  const deleteProject = async () => { if (!remove) return; setDeleting(true); try { await projectService.remove(remove.id); toast.success("Project deleted"); setRemove(null); load(); } catch (e) { toast.error(errorMessage(e)); } finally { setDeleting(false); } };
  return <section><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Projects</h1><p className="text-slate-600">Plan and track your project work.</p></div><Button onClick={() => setForm("new")}>+ New Project</Button></div><div className="mt-6 grid gap-3 sm:grid-cols-[1fr_220px]"><input className="rounded-lg border border-slate-300 px-3 py-2" placeholder="Search projects…" value={search} onChange={(e) => setSearch(e.target.value)} /><Select value={status} onChange={(e) => setStatus(e.target.value as ProjectStatus | "")}><option value="">All statuses</option><option value="NOT_STARTED">Not started</option><option value="IN_PROGRESS">In progress</option><option value="COMPLETED">Completed</option></Select></div>{failed ? <div className="mt-6"><ErrorState onRetry={load} /></div> : loading ? <div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{Array.from({ length: 6 }, (_, i) => <Skeleton key={i} className="h-48" />)}</div> : projects.length === 0 ? <div className="mt-6"><EmptyState title="No projects match your search." action={<Button onClick={() => setForm("new")}>Create your first project</Button>} /></div> : <><div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{projects.map((project) => <article key={project.id} className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><div className="flex justify-between gap-2"><Link className="font-bold text-slate-900 hover:text-indigo-600" to={`/projects/${project.id}`}>{project.name}</Link><Badge tone={tone(project.status)}>{project.status.replace("_", " ")}</Badge></div><p className="mt-2 line-clamp-2 min-h-10 text-sm text-slate-600">{project.description || "No description"}</p><p className="mt-4 text-xs text-slate-500">{showDate(project.startDate)} — {showDate(project.endDate)} · {project.taskCount} tasks</p><div className="mt-4 flex gap-3 text-sm"><button className="font-semibold text-indigo-600" onClick={() => setForm(project)}>Edit</button><button className="font-semibold text-rose-600" onClick={() => setRemove(project)}>Delete</button></div></article>)}</div>{pagination && <Pagination pagination={pagination} onPage={setPage} />}</>}{form && <Modal title={form === "new" ? "New project" : "Edit project"} onClose={() => setForm(null)}><ProjectForm project={form === "new" ? undefined : form} onSave={() => { setForm(null); load(); }} /></Modal>}{remove && <ConfirmDialog message={`Delete “${remove.name}” and all its tasks?`} busy={deleting} onClose={() => setRemove(null)} onConfirm={deleteProject} />}</section>; }
