// Reusable visual building blocks keep all pages consistent and simple.
import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, SelectHTMLAttributes } from "react";
import type { Pagination as PaginationType } from "../types";

const base = "rounded-lg border border-slate-300 px-3 py-2 text-sm outline-none transition focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100";
export function Button({ className = "", children, ...props }: ButtonHTMLAttributes<HTMLButtonElement>) { return <button className={`inline-flex items-center justify-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-indigo-700 disabled:cursor-not-allowed disabled:opacity-60 ${className}`} {...props}>{children}</button>; }
export function Input({ className = "", ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input className={`${base} w-full ${className}`} {...props} />; }
export function Select({ className = "", children, ...props }: SelectHTMLAttributes<HTMLSelectElement>) { return <select className={`${base} w-full bg-white ${className}`} {...props}>{children}</select>; }
export function Spinner({ label = "Loading" }: { label?: string }) { return <span className="inline-flex items-center gap-2"><span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />{label}</span>; }
export function Skeleton({ className = "" }: { className?: string }) { return <div className={`animate-pulse rounded bg-slate-200 ${className}`} />; }
export function Badge({ children, tone = "slate" }: { children: ReactNode; tone?: "slate" | "green" | "yellow" | "red" | "blue" }) { const tones = { slate: "bg-slate-100 text-slate-700", green: "bg-emerald-100 text-emerald-700", yellow: "bg-amber-100 text-amber-700", red: "bg-rose-100 text-rose-700", blue: "bg-sky-100 text-sky-700" }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${tones[tone]}`}>{children}</span>; }
export function EmptyState({ title, action }: { title: string; action?: ReactNode }) { return <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center"><p className="font-medium text-slate-700">{title}</p>{action && <div className="mt-4">{action}</div>}</div>; }
export function ErrorState({ onRetry }: { onRetry: () => void }) { return <div className="rounded-xl bg-rose-50 p-8 text-center text-rose-800"><p className="mb-4 font-medium">We could not load this information.</p><Button onClick={onRetry}>Retry</Button></div>; }
export function Pagination({ pagination, onPage }: { pagination: PaginationType; onPage: (page: number) => void }) { if (pagination.totalPages <= 1) return null; return <div className="flex items-center justify-between pt-5 text-sm"><span>Page {pagination.page} of {pagination.totalPages}</span><div className="flex gap-2"><Button className="bg-slate-700 hover:bg-slate-800" disabled={pagination.page === 1} onClick={() => onPage(pagination.page - 1)}>Previous</Button><Button disabled={pagination.page === pagination.totalPages} onClick={() => onPage(pagination.page + 1)}>Next</Button></div></div>; }
export function Modal({ title, children, onClose }: { title: string; children: ReactNode; onClose: () => void }) { return <div className="fixed inset-0 z-40 grid place-items-center bg-slate-900/50 p-4" role="dialog" aria-modal="true"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-xl bg-white p-6 shadow-xl"><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-bold">{title}</h2><button className="text-2xl text-slate-500" onClick={onClose} aria-label="Close">×</button></div>{children}</div></div>; }
export function ConfirmDialog({ title = "Are you sure?", message, onConfirm, onClose, busy }: { title?: string; message: string; onConfirm: () => void; onClose: () => void; busy?: boolean }) { return <Modal title={title} onClose={onClose}><p className="text-slate-600">{message}</p><div className="mt-6 flex justify-end gap-3"><Button className="bg-slate-700 hover:bg-slate-800" onClick={onClose}>Cancel</Button><Button className="bg-rose-600 hover:bg-rose-700" disabled={busy} onClick={onConfirm}>{busy ? <Spinner label="Deleting" /> : "Delete"}</Button></div></Modal>; }
export function StatCard({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-white p-5 shadow-sm ring-1 ring-slate-200"><p className="text-sm font-medium text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-slate-900">{value}</p></div>; }
